# Generated by Django 4.2 on 2025-04-29 10:41

import apps.users.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.users.managers.UserManager()),
            ],
        ),
    ]
