# Generated by Django 4.2 on 2025-04-28 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookings", "0001_initial"),
        ("flights", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booked_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="flight",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="flights.flight"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="passenger",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="bookings.passenger"
            ),
        ),
    ]
