# Generated by Django 4.2 on 2025-04-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="passenger",
            name="passport_scan",
            field=models.FileField(null=True, upload_to="passengers/documents/"),
        ),
    ]
