# Generated by Django 4.2 on 2025-05-15 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("flights", "0002_alter_airport_city_alter_city_country"),
        ("bookings", "0003_passenger_passport_scan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="booked_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="flight",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="flights.flight",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="passenger",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="bookings.passenger",
            ),
        ),
    ]
