# Generated by Django 4.2 on 2025-05-15 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("airlines", "0003_aircraft_photo_airline_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aircraft",
            name="airline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aircrafts",
                to="airlines.airline",
            ),
        ),
    ]
